PATH=../../go/bin/

all: certs/server-key.pem

#
# Certs
#

certs:
	mkdir -p certs

certs/ca-key.pem: certs
	$(PATH)cfssl gencert -initca ca.json | $(PATH)cfssljson -bare certs/ca

certs/server-key.pem: certs/ca-key.pem
	$(PATH)cfssl gencert \
		-ca=certs/ca.pem \
		-ca-key=certs/ca-key.pem \
		-config=ca-config.json \
		-profile=server \
		server.json | $(PATH)cfssljson -bare certs/server

#
# Clean
#

clean-ca:
	rm -f certs/ca.*

clean-server:
	rm -f certs/server.*

clean: clean-ca clean-server
