---
- name: Secrets
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - secrets
    - secrets/{{ inventory_hostname }}

- name: Dynamic configs
  delegate_to: localhost
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: secrets/{{ inventory_hostname }}/{{ item }}
  loop:
    - ca.json
    - client.json
    - server.json

- name: Static configs
  delegate_to: localhost
  ansible.builtin.copy:
    src: cfssl/{{ item }}
    dest: secrets/{{ inventory_hostname }}/
  loop:
    - Makefile
    - ca-config.json
