---
- name: Build cfssl
  delegate_to: localhost
  environment:
    GOPATH: "{{ playbook_dir }}/go"
  ansible.builtin.command:
    creates: "{{ playbook_dir }}/go/bin/{{ item }}"
    cmd: go install github.com/cloudflare/cfssl/cmd/{{ item }}@{{ cfssl_version }}
  loop:
    - cfssl
    - cfssljson

- name: Secrets
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - secrets
    - secrets/{{ inventory_hostname }}

- name: Dynamic configs
  delegate_to: localhost
  ansible.builtin.template:
    src: "cfssl/{{ item }}.j2"
    dest: secrets/{{ inventory_hostname }}/{{ item }}
  loop:
    - ca.json

- name: Server config
  delegate_to: localhost
  ansible.builtin.template:
    src: cfssl/server.json.j2
    dest: secrets/{{ inventory_hostname }}/server.json

- name: Makefile config
  delegate_to: localhost
  ansible.builtin.template:
    src: "cfssl/Makefile.j2"
    dest: secrets/{{ inventory_hostname }}/Makefile
  loop: "{{ reverst_groups.keys() }}"

- name: Static configs
  delegate_to: localhost
  ansible.builtin.copy:
    src: cfssl/{{ item }}
    dest: secrets/{{ inventory_hostname }}/
  loop:
    - ca-config.json

- name: Make all the SSL stuff
  delegate_to: localhost
  ansible.builtin.command:
    cmd: make
    chdir: secrets/{{ inventory_hostname }}/
    creates: secrets/{{ inventory_hostname }}/certs/client.pem
