---
- name: Src folder
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - ./src
    - ./src/reverst

- name: Fetch git source
  delegate_to: localhost
  ansible.builtin.git:
    repo: https://github.com/flipt-io/reverst.git
    dest: ./src/reverst
    version: "{{ reverst_version }}"

- name: Build reverst client
  delegate_to: localhost
  environment:
    GOPATH: "{{ playbook_dir }}/go"
  ansible.builtin.command:
    creates: "{{ playbook_dir }}/go/bin/reverst"
    chdir: ./src/reverst
    cmd: go install ./client/...

- name: User
  ansible.builtin.user:
    name: reverst
    system: true

- name: Build reverstd server
  delegate_to: localhost
  environment:
    GOOS: linux
    GOARCH: "{{ reverts_archi }}"
  ansible.builtin.command:
    chdir: ./src/reverst
    cmd: go build ./cmd/reverstd

- name: Reverst folder
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt
    - /opt/reverst
    - /opt/reverst/{{ reverst_version }}

- name: Deploy binary
  ansible.builtin.copy:
    src: ../../src/reverst/reverstd
    dest: /opt/reverst/{{ reverst_version }}/reverstd
    mode: "0750"
    owner: root
    group: reverst

- name: Link current version
  ansible.builtin.file:
    state: link
    src: /opt/reverst/{{ reverst_version }}/reverstd
    dest: /usr/local/bin/reverstd
    owner: root
    group: root
    mode: "0755"

# Config

- name: Etc folder
  ansible.builtin.file:
    path: /etc/reverst
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: SSL stuff
  ansible.builtin.copy:
    src: ../../secrets/{{ inventory_hostname }}/certs/{{ item }}
    dest: /etc/reverst/
    owner: root
    group: reverst
    mode: "0640"
  loop:
    - ca.pem
    - server.pem
    - server-key.pem
